### PR TITLE
Fix generated group by. Closes #23

### LINKED ISSUE #23: distinct group by issue
the auto-generated group by is invalid:
`GROUP BY ct_campaign.end_date asc`

AQL:

```
            distinct ct_campaign {
                id as ct_campaign_id,
                name,
                slug
                where ( archive = 0 or archive is null )
                order by end_date asc, iorder, name
            }
```

Genereated SQL:

```
SELECT distinct  ct_campaign.id as "ct_campaign_id", 
ct_campaign.name as "name", 
ct_campaign.slug as "slug" 
 FROM ct_campaign as ct_campaign 
 WHERE  ct_campaign.active = 1 AND  ( ct_campaign.archive = 0 or ct_campaign.archive is null )  
GROUP BY ct_campaign.end_date asc, ct_campaign.iorder, ct_campaign.name, ct_campaign.id, ct_campaign.slug, ct_campaign.end_date 
ORDER BY ct_campaign.end_date asc, ct_campaign.iorder, ct_campaign.name 
```

### PR DESCRIPTION
**Pull request by stanistan**

### CODE REVIEW

File: lib/core/class.aql2array.php [hunk 1]
```diff
@@ -360,10 +360,15 @@ public function init($aql, $parent = null) {
...
+				$o_arr = array(' asc', ' ASC', ' desc', ' DESC');
+				$clean_order = function($t) use($o_arr) {
+					return str_replace($o_arr, '', $t);
+				};
+
 				foreach ($split_info['order by'] as $k) {
 					if (!in_array($k, $split_info['group by'])) {
-
-						$split_info['group by'][] = $k;
+						$split_info['group by'][] = $clean_order($k);
```
Comment (stanistan) [inline lib/core/class.aql2array.php:371]: Strips out everything in `$o_arr` from the group by

**Comment by stanistan** [comment]
It would take about a day to use this fix or a `$_GET['refresh']`, since the parsed aqlarray is stored.
